version: '2'
services:
    jhsample-app:
        image: jhsample
        external_links:
            - jhsample-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhsample?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    jhsample-mysql:
        extends:
            file: mysql.yml
            service: jhsample-mysql
